#!/bin/bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="${1:-$PROJECT_ROOT/api-surface.txt}"

CLASSES=(
    "force-app/main/default/classes/Async.cls"
    "force-app/main/default/classes/queue/QueueableJob.cls"
    "force-app/main/default/classes/queue/QueueableBuilder.cls"
    "force-app/main/default/classes/queue/QueueableManager.cls"
    "force-app/main/default/classes/batch/BatchableBuilder.cls"
    "force-app/main/default/classes/batch/BatchableManager.cls"
    "force-app/main/default/classes/schedule/SchedulableBuilder.cls"
    "force-app/main/default/classes/schedule/SchedulableManager.cls"
    "force-app/main/default/classes/schedule/CronBuilder.cls"
    "force-app/main/default/classes/mocks/AsyncMock.cls"
)

{
    echo "# Async Lib — API Surface Snapshot"
    echo "# This file is auto-generated by: ./scripts/generate-api-surface.sh"
    echo "# Any diff to this file means the public API changed — review carefully."
    echo "# Every public method in this unlocked package is a permanent contract."
    echo "#"
    echo "# Regenerate after code changes: ./scripts/generate-api-surface.sh"
    echo ""

    for cls in "${CLASSES[@]}"; do
        filepath="$PROJECT_ROOT/$cls"
        [ -f "$filepath" ] || continue
        classname=$(basename "$cls" .cls)
        echo "=== $classname ==="

        grep -n '^\s*public\s' "$filepath" \
            | grep -v '^\s*public\s\+\(inherited\|with\|without\)\s\+sharing\s\+class' \
            | sed 's/^[[:space:]]*//' \
            | sed 's/{[[:space:]]*$//' \
            | sed 's/[[:space:]]*$//' \
            | sort -t: -k2,2

        echo ""
    done
} > "$OUTPUT"

echo "API surface written to: $OUTPUT"
echo "Lines: $(wc -l < "$OUTPUT")"
